void        ft_bzero(void *mem, size_t size);
char        *ft_strcat(char *, const char *);
char        *ft_strcat(char *, const char *);
int         ft_isalpha(int);
int         ft_isdigit(int);
int         ft_isalnum(int);
int         ft_isascii(int);
int         ft_isprint(int);
int         ft_toupper(int);
int         ft_tolower(int);
void        ft_putstr(char const *s);
size_t      ft_strlen(const char *);
char        *ft_strcpy(char *, const char *);
char        *ft_strdup(const char *);
void        *ft_memset(void *, int, size_t);
void		*ft_memcpy(void *, const void *, size_t);
void		ft_puts(char const *s);
void		ft_cat(int fd);
